/**
 * Catalogo prodotti (estratto dal listino interno). Nessun prezzo:
 * i prezzi sono riservati ai clienti e vanno richiesti via contatto.
 */
export const CATEGORIES = [
  {
    id: "formaggi",
    title: "Formaggi & Latticini",
    description:
      "Mozzarelle, formaggi freschi e stagionati, DOP e specialità per pizzerie, gastronomie e ristoranti.",
    products: [
      { name: "Mozzarella Fior di Latte", format: "Bocconcini 125 g" },
      { name: "Mozzarella per Pizza", format: "Bocce, vasca 4,5 kg" },
      { name: "Mozzarella per Pizza Julienne", format: "Latte UE, alta qualità / taglio Napoli" },
      { name: "Mozzarella Filoni Bayerland", format: "1 kg" },
      { name: "Mozzarella di Bufala Campana DOP", format: "Aversana o bocconcini, busta 250 g" },
      { name: "Ciliegine di Mozzarella", format: "In acqua, al kg" },
      { name: "Burrata Vaccina", format: "Singola 125 g" },
      { name: "Stracciatella", format: "250 g" },
      { name: "Scamorze Bianche Affumicate", format: "Prodotto artigianale" },
      { name: "Provola Affumicata", format: "1-2 kg" },
      { name: "Provola Silana DOP", format: "Forma intera, circa 1,2 kg" },
      { name: "Caciocavallo Stagionato Cremona", format: "Al kg" },
      { name: "Ricotta da Lavorazione", format: "Sottovuoto, circa 4-5 kg" },
      { name: "Stracchino", format: "Pancetto 1 kg / vasca circa 2 kg" },
      { name: "Gorgonzola DOP 1/8", format: "Sostenuta o più morbida, circa 1,5 kg" },
      { name: "Edamer", format: "Intero circa 3 kg / a fette in vaschetta 1 kg" },
      { name: "Brie", format: "Forma circa 1 kg" },
      { name: "Taleggio DOP", format: "Forma intera, circa 2 kg" },
      { name: "Mascarpone", format: "Vaschetta 500 g" },
      { name: "Grana Padano DOP", format: "1/16 spicchio, scaglie o grattugiato" },
      { name: "Parmigiano Reggiano DOP 24 mesi", format: "Spicchio 1/8, circa 5 kg" },
      { name: "Pecorino Sardo DOP", format: "Dolce o stagionato" },
      { name: "Fontal", format: "1/4 spicchio, circa 3 kg" },
      { name: "Burro", format: "Pancetto 1 kg" },
      { name: "Panna da Cucina e da Montare", format: "Brik 200 ml / 500 ml / 1 L" },
      { name: "Formaggio Spalmabile", format: "Secchiello / vasca 1,5 kg" },
    ],
  },
  {
    id: "salumi",
    title: "Salumi & Affettati",
    description:
      "Prosciutti, salami, bresaola e specialità di salumeria, standard o alta qualità, interi o al taglio.",
    products: [
      { name: "Prosciutto Cotto", format: "Standard, scelto, alta resa o senza cotenna" },
      { name: "Prosciutto Cotto Alta Qualità / Lenta Cottura", format: "Intero o metà" },
      { name: "Prosciutto Crudo", format: "Standard o selezione" },
      { name: "Prosciutto Crudo di Parma DOP", format: "Stagionatura min. 14 mesi, disossato" },
      { name: "Bresaola Punta d'Anca", format: "Sottovuoto" },
      { name: "Carpaccio di Bresaola", format: "Sottovuoto" },
      { name: "Arrosto di Tacchino", format: "Lenta cottura o a metà sottovuoto" },
      { name: "Speck", format: "Intero o metà sottovuoto" },
      { name: "Mortadella con Pistacchi", format: "Al taglio" },
      { name: "Pancetta", format: "Arrotolata artigianale o stesa affumicata" },
      { name: "Salame Milano / Napoli", format: "A metà sottovuoto" },
      { name: "Salame Crespone Casereccio", format: "Al taglio" },
      { name: "Nduja", format: "Tipica calabrese, sottovuoto" },
      { name: "Wurstel", format: "Puro suino o pollo e tacchino" },
      { name: "Spianata Piccante", format: "Linea competitiva o stagionatura garantita" },
      { name: "Capocollo Piccante", format: "Sottovuoto" },
      { name: "Guanciale", format: "Nazionale o stagionato" },
      { name: "Porchetta", format: "Trancio sottovuoto, pronta all'uso" },
      { name: "Roast-Beef", format: "Sottovuoto" },
      { name: "Manzo Stufato / Carne Salada", format: "Sottovuoto" },
    ],
  },
  {
    id: "conserve",
    title: "Conserve & Sott'oli",
    description:
      "Olive, funghi, pomodoro, tonno e sott'oli selezionati per cucina e attività di ristorazione.",
    products: [
      { name: "Olive Nostraline", format: "Denocciolate secchio 5 kg o in salamoia" },
      { name: "Olive Taggiasche", format: "Vaso vetro in olio, 1,5 kg" },
      { name: "Capperi sotto Sale", format: "Secchiello 1 kg" },
      { name: "Funghi Champignon", format: "Al naturale o trifolati" },
      { name: "Funghi Porcini", format: "In latta" },
      { name: "Carciofi", format: "A fettine al naturale, spicchi in olio o trifolati" },
      { name: "Polpa di Pomodoro", format: "Cartone da 15 kg (lattine) o bag" },
      { name: "Pomodori Pelati", format: "Cartone da 15 kg, prima scelta o standard" },
      { name: "Tonno in Olio d'Oliva o Girasole", format: "80 g / 600 g / 1630 g" },
      { name: "Tonno Pinna Gialla", format: "In olio d'oliva, 1730 g" },
      { name: "Acciughe in Olio", format: "Vaso vetro o latta, alta qualità disponibile" },
      { name: "Salsa Tartufata", format: "Scura o chiara, vaso 500 g" },
      { name: "Crema di Porcini", format: "Vaso 500 g" },
      { name: "Friarielli / Scarole alla Napoletana", format: "Vaso vetro" },
      { name: "Pomodorini Rossi o Gialli Semidried", format: "Vaso vetro" },
    ],
  },
];
